### ISSUE TITLE
Log spam of rendering player

### ISSUE THREAD

**Issue by Joshwoo70** [Mysteryem/Up_And_Down_And_All_Around#66]
```[20:13:42] [Client thread/WARN] [FML]: ****************************************
[20:13:42] [Client thread/WARN] [FML]: * Tried rendering player <USERNAME>, but their bounding box was not a GravityAxisAlignedBB
[20:13:42] [Client thread/WARN] [FML]: *  at uk.co.mysterymayhem.gravitymod.client.listeners.EntityRenderListener.onRender(EntityRenderListener.java:82)
[20:13:42] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_884_EntityRenderListener_onRender_Pre.invoke(.dynamic)
[20:13:42] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[20:13:42] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[20:13:42] [Client thread/WARN] [FML]: *  at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:58)
[20:13:42] [Client thread/WARN] [FML]: *  at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)...
[20:13:42] [Client thread/WARN] [FML]: ****************************************
```

issue is here : https://github.com/Mysteryem/Up_And_Down_And_All_Around/blob/master/src/main/java/uk/co/mysterymayhem/gravitymod/client/listeners/EntityRenderListener.java#L80-L84

This creates an issue where : 
> MultiMC stopped watching the game log because the log length surpassed 100000 lines.
You may have to fix your mods because the game is still logging to files and likely wasting harddrive space at an alarming rate!

FML Log file size:
![screenshot 2017-04-25 20 45 41](https://cloud.githubusercontent.com/assets/7894419/25385967/44fd2d58-29f8-11e7-8805-e83b5dd221d3.png)

Suggestion : introduce a method of culling this log spam, or remove it entirely

**Comment by Mysteryem** [comment]
I'm going to guess there's some mod in your pack which has something like fake players, seeing as the player's name in your log is `<USERNAME>`. If not, could you provide me with a modlist please?

The log message is there because for normal players, it indicates that this mod is completely non-functional.

I hadn't considered other mods creating their own player-like mobs with custom bounding box handling. I'll hotfix this. Thank you for bringing it to my attention.

**Comment by Mysteryem** [comment]
Hotfixed in https://github.com/Mysteryem/Up_And_Down_And_All_Around/commit/cb757599aa54da4ae86e932cbe8a02ecac4aaf8a

Keep an eye on curse for when 2.7.1 gets approved.

**Comment by Joshwoo70** [comment]
<USERNAME> is the name of a any player

**Comment by Forecaster** [comment]
I'd guess it's the lootable bodies mod
