### ISSUE TITLE
My server was crashed when I join it.I use sponge server.1.10.2

### ISSUE THREAD

**Issue by le10077** [Mysteryem/Up_And_Down_And_All_Around#71]
WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.10.2-2254-5.2.0-BETA-2250.jar)
  mysttmtgravitymod (UpAndDownAndAllAround-1.10.2-2.7.3.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 17-7-2 12:46
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.entity.player.EntityPlayer.func_96124_cp(EntityPlayer.java:2248)
	at net.minecraft.entity.player.EntityPlayer.func_145748_c_(EntityPlayer.java:2255)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:800)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:455)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Mysteryem** [comment]
Please provide the full crash report.

**Comment by le10077** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.10.2-2254-5.2.0-BETA-2250.jar)
  mysttmtgravitymod (UpAndDownAndAllAround-1.10.2-2.7.3.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 17-7-2 下午12:46
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.entity.player.EntityPlayer.func_96124_cp(EntityPlayer.java:2248)
	at net.minecraft.entity.player.EntityPlayer.func_145748_c_(EntityPlayer.java:2255)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:800)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:455)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3151911152 bytes (3005 MB) / 4136108032 bytes (3944 MB) up to 4136108032 bytes (3944 MB)
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254-universal.jar) 
	UCHIJAAAA	spongeapi{5.2.0-SNAPSHOT-a3257a0} [SpongeAPI] (minecraft.jar) 
	UCHIJAAAA	sponge{1.10.2-2254-5.2.0-BETA-2250} [SpongeForge] (spongeforge-1.10.2-2254-5.2.0-BETA-2250.jar) 
	UCHIJAAAA	mysttmtgravitymod{2.7.3} [Up And Down And All Around] (UpAndDownAndAllAround-1.10.2-2.7.3.jar) 
	UCHIJAAAA	nucleus{0.28.1-S5.1} [Nucleus] (Nucleus-0.28.1-1.10.2-S5.1-plugin.jar) 
	UCHIJAAAA	pvptoggle{1.2.0} [PvpToggle] (PvPToggle-1.2.0.jar) 
	UCHIJAAAA	helpme{04e93bdc44} [build] (projectportals-6.0.0-0.13.8.jar) 
	UCHIJAAAA	pjp{0.13.8} [ProjectPortals] (projectportals-6.0.0-0.13.8.jar) 
	UCHIJAAAA	better-command-signs{0.0.1} [Better Command Signs] (BetterCommandSigns-0.0.4.jar) 
	UCHIJAAAA	spongenationtag{1.1} [Sponge Nation Chat Tag] (Nations-2.4.jar) 
	UCHIJAAAA	nations{2.4} [Nations] (Nations-2.4.jar) 
	UCHIJAAAA	catclearlag{0.7.1} [CatClearLag] (CatClearLag-0.7.1.jar) 
	UCHIJAAAA	jobslite{1.7.0} [JobsLite] (JobsLite-1.7.0 (1).jar) 
	UCHIJAAAA	boop{1.4.1} [Boop] (Boop-1.4.1.jar) 
	UCHIJAAAA	customcommands{1.0} [CustomCommands] (PermissionManager-2.6.0-API-5.X-6.X.jar) 
	UCHIJAAAA	permissionmanager{2.6.0} [PermissionManager] (PermissionManager-2.6.0-API-5.X-6.X.jar) 
	UCHIJAAAA	deathpenalty{v1.1} [DeathPenalty] (deathpenalty-v1.1.jar) 
	UCHIJAAAA	activetime{mc1.10.2-v1.0.3} [ActiveTime] (ActiveTime-mc1.10.2-v1.0.3.jar) 
	UCHIJAAAA	clearmob{1.3.3} [ClearMob] (ClearMob-1.3.3.jar) 
	UCHIJAAAA	playershopsrpg{1.1.0} [PlayerShopsRPG] (PlayerShopsRPG-v1.1.0 (1).jar) 
	UCHIJAAAA	flexiblelogin{0.8} [FlexibleLogin] (FlexibleLogin.jar) 
	UCHIJAAAA	minereset{1.0.7} [MineReset] (MineReset-1.0.7.jar) 
	UCHIJAAAA	economylite{2.10.1} [EconomyLite] (EconomyLite-5.0.0-2.10.1.jar) 
	UCHIJAAAA	autobroadcaster{0.2.1} [AutoBroadcaster] (AutoBroadcasterSponge-0.2.1.jar) 
	UCHIJAAAA	triviaquest{mc1.10.2-v1.3.0} [TriviaQuest] (TriviaQuest-mc1.10.2-v1.3.0.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.10.2-2254-5.2.0-BETA-2250.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
mysttmtgravitymod (UpAndDownAndAllAround-1.10.2-2.7.3.jar)
  uk.co.mysterymayhem.gravitymod.asm.Transformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 35; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by Mysteryem** [comment]
Thank you. If you can confirm that if you remove UpAndDownAndAllAround, the crash no longer occurs, that would be great too.

**Comment by le10077** [comment]
Thanks for your reply.
I just added some server plugins and this Mod.

**Comment by le10077** [comment]
yes.when I remove it. I can join the game.

**Comment by Flashback083** [comment]
Hello ! I dont know if you always work on this mod but i have also this crash with sponge and your mod in 1.12.2 <_<
I really want to play on server with this mod :c 
Tell me if you want any information !!
